import myHeader from "./components/myHeader.js";
import myBanner from "./components/myBanner.js";
import myPost from "./components/myPost.js";
import myArticles from "./components/myArticles.js";
import myAside from "./components/myAside.js";
import myFooter from "./components/myFooter.js";
myHeader.show();
myBanner.showImage();
myBanner.show2();
myPost.show3();
myArticles.show4();
myAside.show5(); 
myFooter.show6();